### ISSUE TITLE
BEAUti won't allow me to save .xml file due to priors

### ISSUE THREAD

**Issue by MacauleyLockeml** [beast-dev/beast-mcmc#1167] opened 2024-02-13 18:01 UTC
I am currently trying to build the .xml file using BEAUti. However after doing all the adjustments a pop-up for unchanged priors appears that is empty and won't allow me to save the .xml file.

I don't know if this is just an issue with me or a more common issue.

![Screenshot 2024-02-13 at 10 59 46 AM](https://github.com/beast-dev/beast-mcmc/assets/58670342/f2efd6c2-cfe7-4870-8262-78755fa2b3a4)

**Comment by tarcioroca** [comment] 2024-02-14 00:53
I'm also having the same problem. I'm a Mac user.

**Comment by judyssister** [comment] 2024-03-03 13:08
Same. I am also a Mac user with macOS Sonoma 14.3.1 and beast 1.10.4. After I click generate beast file and continue, the windows that used to generate the XML files don no show up.

**Comment by RicardoRH96** [comment] 2024-03-14 18:09
I'm having the same issue.

**Comment by rambaut** [comment] 2024-04-02 13:23
Is this the same issue as #1172? I am unable to reproduce this.

**Comment by rambaut** [comment] 2024-04-27 15:00
Unable to reproduce this. Closing until more information

**Closed** 2024-04-27 15:01 UTC
Labels: bug, beauti
