### ISSUE TITLE
Combine discrete traits into one partition?

### ISSUE THREAD

**Issue by sanderdebacker** [beast-dev/beast-mcmc#1161] opened 2023-09-07 12:21 UTC
I'm importing a mapping file containing the present (Y) or absent (N) state for each taxon in the data partition across 90 traits.
When selecting all discrete traits and creating a partition, it creates one for each trait.
I'm used to continuous traits where for example I'm able to combine latitude and longitude (as two different traits) into one partition.

Is this possible for discrete traits?

**Comment by gabehassler** [comment] 2023-09-07 18:08
Hi @sanderdebacker, the answer depends on why you want to combine the 90 traits into a single partition. Likely there is a solution that is implemented in BEAST but not available in BEAUti.

The solution will probably involve a combination of a latent liability model to map your discrete traits to a continuous space and a latent factor model for dimension reduction (90 traits is a lot for a joint trait model).

I'm closing this issue because it's not a bug in BEAST, but I'm happy to discuss specifics further on the BEAST users google group (https://groups.google.com/g/beast-users).

**Closed by gabehassler** 2023-09-07 18:08 UTC
