### ISSUE TITLE
Missing char '?' poorly read by BEAUti on some Windows systems

### ISSUE THREAD

**Issue by msuchard** [beast-dev/beast-mcmc#833] opened 2016-08-18 01:30 UTC
Generates invalid XML during bat rabies tutorial.  Workaround is to manually edit XML, re-adding ? into missing traits (2 of them).

Java language issue?

**Comment by rambaut** [comment] 2017-07-19 09:01
Can anyone debug this on a Windows machine?

**Comment by rambaut** [comment] 2018-06-10 11:38
Pushing this forward because I am unable to test. Work around for tutorial is  to replace the ? with another symbol?

**Comment by GuyBaele** [comment] 2018-08-08 15:46
Unable to reproduce on an XML created with BEAUti v1.10.0 on Windows 8.1 Pro, Java SE Runtime Environment 8u181 and could run the XML without problems on the same system using BEAST v1.10.0 and BEAGLE v3.0.1.

**Comment by rambaut** [comment] 2024-06-16 17:37
Closing on the basis that it couldn't be reproduced

**Closed by rambaut** 2024-06-16 17:37 UTC
Labels: bug, help wanted, beauti
