### ISSUE TITLE
win10 import data dialog

### ISSUE THREAD

**Issue by hildebra** [beast-dev/beast-mcmc#886] opened 2017-05-16 13:26 UTC
Whenever I try to import data by clicking "File->Import data..." Beauti (v1.8.4) just crashed. Error log is attached.
I am using win10 64bit, creators update

[hs_err_pid7468.zip](https://github.com/beast-dev/beast-mcmc/files/1004494/hs_err_pid7468.zip)

**Comment by rambaut** [comment] 2017-06-01 12:35
This is not a bug in BEAST. The error is coming from the internals of Windows when a native call is made (to bring up a file dialog box). I am unable to replicate the error so am closing the issue. I suggest this is posted to the beast-user group to see if anyone else has had a similar problem.

**Closed by rambaut** 2017-06-01 12:35 UTC
